// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBfsG6IYpt_6_XegOdGcw04MY4hS0INQ',
    appId: '1:374389052793:web:67f2b05387a5aaa6720ba8',
    messagingSenderId: '374389052793',
    projectId: 'dyslexiamate-8f477',
    authDomain: 'dyslexiamate-8f477.firebaseapp.com',
    storageBucket: 'dyslexiamate-8f477.firebasestorage.app',
    measurementId: 'G-0GE0HVWQ6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLvV_JA7qQAROMKsdzKH2HUZmL_sxq2A',
    appId: '1:374389052793:android:a0a60317e99ea1af720ba8',
    messagingSenderId: '374389052793',
    projectId: 'dyslexiamate-8f477',
    storageBucket: 'dyslexiamate-8f477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpWpBrq5ItnUw4doWB5UeMZWVZ7yxRYr0',
    appId: '1:374389052793:ios:f7d9de487ca4c442720ba8',
    messagingSenderId: '374389052793',
    projectId: 'dyslexiamate-8f477',
    storageBucket: 'dyslexiamate-8f477.firebasestorage.app',
    iosBundleId: 'com.example.dyslexiaMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpWpBrq5ItnUw4doWB5UeMZWVZ7yxRYr0',
    appId: '1:374389052793:ios:f7d9de487ca4c442720ba8',
    messagingSenderId: '374389052793',
    projectId: 'dyslexiamate-8f477',
    storageBucket: 'dyslexiamate-8f477.firebasestorage.app',
    iosBundleId: 'com.example.dyslexiaMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBfsG6IYpt_6_XegOdGcw04MY4hS0INQ',
    appId: '1:374389052793:web:640d2b7d6e798df4720ba8',
    messagingSenderId: '374389052793',
    projectId: 'dyslexiamate-8f477',
    authDomain: 'dyslexiamate-8f477.firebaseapp.com',
    storageBucket: 'dyslexiamate-8f477.firebasestorage.app',
    measurementId: 'G-G8LL27VX0D',
  );
}
